# docker-compose.yml
services:
  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app:cached
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: shegmant
      POSTGRES_DB: student_rooms
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./server/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./server/db/rutelinii.sql:/docker-entrypoint-initdb.d/1_rutelinii.sql

volumes:
  postgres-data:
